## Application Name
spring:
  application:
    name: ntsk-web-server

## Message Configuration
  messages:
    basename: messages
    encoding: UTF-8

## Web Configuration
server:
  port: 8080

## Logging
logging: 
  config: classpath:logback.xml

# MQ
spring.activemq:
  broker-url: tcp://NPC070:61616?jms.prefetchPolicy.queuePrefetch=1
  #broker-url: tcp://localhost:61616?jms.prefetchPolicy.queuePrefetch=1
  user: admin
  password: secret
  pool:
    enabled: true
    max-connections: 50

spring.jms:
  listener:
    concurrency: 5          # 同時コンシューマーの最小数
    max-concurrency: 10     # 同時コンシューマーの最大数
  cache:
    session-cache-size: 5   #

